### ISSUE TITLE
cidian包安装错误

### ISSUE THREAD

**Issue by fjj2617** [qinwf/cidian#2]
你好，在安装了Rtools和相关R包之后，提示cidian包安装错误：Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Problem with the SSL CA cert (path? access rights?)

**Comment by qinwf** [comment]
这个错误提示是 SSL 证书错误，可能是电脑没有安装对应的根证书，或者根证书无法被读取，或者网络中有中间人攻击。


`?download.file`


> Secure URLs
> 
> Methods which access https:// and ftps:// URLs should try to verify their certificates. This is usually done using the CA root certificates installed by the OS (although we have seen instances in which these got removed rather than updated). For further information see http://curl.haxx.se/docs/sslcerts.html.
> 
> This is an issue for method = "libcurl" on Windows, where the OS does not provide a suitable CA certificate bundle, so by default on Windows certificates are not verified. To turn verification on, set environment variable CURL_CA_BUNDLE to the path to a certificate bundle file, usually named ‘ca-bundle.crt’ or ‘curl-ca-bundle.crt’. (This is normally done for a binary installation of R, which installs ‘R_HOME/etc/curl-ca-bundle.crt’ and sets CURL_CA_BUNDLE to point to it if that environment variable is not already set.) For an updated certificate bundle, see http://curl.haxx.se/docs/sslcerts.html. Currently one can download a copy from https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt and set CURL_CA_BUNDLE to the full path to the downloaded file.


可以尝试修改 options("download.file.method")， 或者按照上面的说明，安装根证书。

**Comment by qinwf** [comment]
这个是网络错误，包还没有下载，不是安装过程中出现的错误哈。

**Comment by fjj2617** [comment]
在安装cidian包之前的其他几个包都没有问题，为什么cidian包就会网络错误，要怎么解决



fjj2617@163.com
 
发件人： qinwf
发送时间： 2016-12-26 18:00
收件人： qinwf/cidian
抄送： fjj2617; Author
主题： Re: [qinwf/cidian] cidian包安装错误 (#2)
这个是网络错误，包还没有下载，不是安装过程中出现的错误哈。
―

**Comment by qinwf** [comment]
因为 install_github 函数是从 GitHub 安装包，而不是从 CRAN 安装。从 CRAN 安装，根据选择的镜像，国内大部分镜像是使用的 HTTP 协议，没有使用 HTTPS 协议，可能你选择镜像是 HTTP 协议的，内容是明文传输没有加密的，不需要 SSL 证书。

GitHub 只有 HTTPS 加密协议的下载方式，不支持明文的 HTTP 协议，HTTPS 协议传输过程中需要 SSL 证书加密。国内的网络有的时候后偶尔抽风，和谐 GitHub 的网络，也有可能导致 HTTPS 证书错误。之前沃通证书事件就是国内的卖 SSL 证书的企业，乱发 GitHub 的 SSL 证书，想想都可怕。

http://www.freebuf.com/news/113297.html

解决办法有，安装 SSL 证书 

> This is an issue for method = "libcurl" on Windows, where the OS does not provide a suitable CA certificate bundle, so by default on Windows certificates are not verified. To turn verification on, set environment variable CURL_CA_BUNDLE to the path to a certificate bundle file, usually named ‘ca-bundle.crt’ or ‘curl-ca-bundle.crt’. (This is normally done for a binary installation of R, which installs ‘R_HOME/etc/curl-ca-bundle.crt’ and sets CURL_CA_BUNDLE to point to it if that environment variable is not already set.) For an updated certificate bundle, see http://curl.haxx.se/docs/sslcerts.html. Currently one can download a copy from https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt and set CURL_CA_BUNDLE to the full path to the downloaded file.

或者 options("download.file.method") 为 libcurl 以外的值。

建议安装证书，安全一些。

**Comment by fjj2617** [comment]
谢谢您的讲解，但是对SSL的安装不太明白

**Comment by qinwf** [comment]
设置 Windows 环境变量 CURL_CA_BUNDLE 为 SSL 根证书的目录，SSL 根证书可以下载这个文件 https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt 

 `R 默认安装目录/etc/curl-ca-bundle.crt` 应该也有一份 curl-ca-bundle.crt ，也可以把 CURL_CA_BUNDLE 的值设为这个目录。 

设置环境变量后，重启 Windows。

**Comment by fjj2617** [comment]
配置完环境变量之后，执行library(devtools)；install_github("qinwf/cidian")之后，出现新的问题了
Downloading GitHub repo qinwf/cidian@master
from URL https://api.github.com/repos/qinwf/cidian/zipball/master
Installing cidian
"F:/R-3.3.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  "C:/Users/Administrator/AppData/Local/Temp/Rtmp8kf8zA/devtools92c8307ad6/qinwf-cidian-3002bf4"  \
  --library="F:/R-3.3.2/library" --install-tests 

* installing *source* package 'cidian' ...
** libs

*** arch - i386
C:/Program Files (x86)/Rtools/mingw_32/bin/g++  -std=c++0x -I"F:/R-33~1.2/include" -DNDEBUG -I../inst/include -DLOGGER_LEVEL=LL_WARN   -I"F:/R-3.3.2/library/Rcpp/include" -I"F:/R-3.3.2/library/RcppProgress/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
Syntax error: "(" unexpected
make: *** [RcppExports.o] Error 2
Warning: 运行命令'make -f "Makevars.win" -f "F:/R-33~1.2/etc/i386/Makeconf" -f "F:/R-33~1.2/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="cidian.dll" OBJECTS="RcppExports.o loaddict.o unicode.o"'的状态是2
ERROR: compilation failed for package 'cidian'
* removing 'F:/R-3.3.2/library/cidian'
错误: Command failed (1)

**Comment by qinwf** [comment]
Rtools 是 R 包编译工具，如果只是使用 R 包的话一般是不需要安装的，如果需要开发 R 包的话，偶尔需要使用到它来进行编译包含 C 和 C++ 的代码。它的安装目录和 R 的安装目录不一样，因为 Rtools 里包含了 gcc 等 C++ 等的编译工具。

CRAN 上的包都是使用 Rtools 编译好了的，用户不需要安装 Rtools 就可以直接安装 CRAN 上的包。我计划下个月把这个包发到 CRAN 上吧，这样大家安装起来方便一些。

**Comment by fjj2617** [comment]
非常感谢，cidian包已经安装完成，后期使用过程中有问题还需要向您请教
